
default: &default
  adapter: postgresql
  encoding: unicode
  database: blog_desafio
  username: admin
  password: admin
  host: localhost

development:
  <<: *default

production:
  <<: *default
  database: blog_desafio_production
